/**
 * Growa Qatar - Database Types
 * Step 0.5: Supabase bootstrap artifacts
 * 
 * This file will be auto-generated by Supabase CLI:
 * npx supabase gen types typescript --local > supabase/types/database.ts
 * 
 * DO NOT EDIT MANUALLY - This file should be regenerated after each migration.
 * 
 * Type generation will be populated after Phase 1 migrations.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be defined in Phase 1
      // - country_instances
      // - organizations
      // - departments
      // - profiles
      // - memberships
      // - role_templates
      // - permission_templates
      // - invitations
      // - audit_logs
    }
    Views: {
      // Views will be defined as needed
    }
    Functions: {
      // Functions will be defined as needed
    }
    Enums: {
      // Enums will be defined in Phase 1
      // - organization_type
      // - membership_status
      // - invitation_status
      // - audit_action
    }
    CompositeTypes: {
      // Composite types will be defined as needed
    }
  }
}

// Placeholder types - will be replaced by generated types
export type Tables<T extends keyof Database['public']['Tables']> = 
  Database['public']['Tables'][T]

export type Enums<T extends keyof Database['public']['Enums']> = 
  Database['public']['Enums'][T]
